### ISSUE TITLE
Failed DNS Lookup

### ISSUE THREAD

**Issue by wayne-david** [Azure/iot-hub-device-update-yocto#6]
![du-sample](https://user-images.githubusercontent.com/40905642/232841177-2d94fd98-01e3-49aa-a6c4-59bb64099f6a.PNG)
![dns_error](https://user-images.githubusercontent.com/40905642/232839872-9bc35db5-f6fb-4094-a02d-f9c138b9ef6b.PNG)
I tried implementing azure-device-update using this repository but ran into an issue.It builds correctly but agent fails to connect to Azure .Here is the Error and my sample du-config.json. Kindly assist.

**Comment by jw-msft** [comment]
In the logs, the mqtt transport layer is showing socket failure due to DNS lookup failure. On the device's shell, does a dns lookup for the same host also fail? You can check the config there against the expected DNS configuration. Are there specific dns server(s) required for the network environment of the device? Are the firewall rules on the network nodes along the route allowing DNS traffic?
